source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TestPodsF_Example', :exclusive => true do
  pod 'TestPodsF', :path => '../'
end

target 'TestPodsF_Tests', :exclusive => true do
  pod 'TestPodsF', :path => '../'

  
end
